name: CD - lambda-sam

on:
    workflow_run:
      workflows: [CI - lambda-sam]
      types: [requested]
      branches: ["main"]

permissions:
  id-token: write
  contents: write    

jobs:

    sam-validate-build:
        
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.8"]
    
        steps:
    
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
              aws-region: ${{ secrets.AWS_REGION }}
    
          - name: SAM Validate
            run: |
                sam validate
    
          - name: SAM Build
            run: |
              sam build 