name: Run Python tests

on:
  push:
    branches: ["main"]

jobs:

  build-scan-trivy-repo:
      name: Run trivy
      runs-on: ubuntu-latest

      steps:

        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Build an image from Dockerfile
          run: |
            docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'

  build-test-pytest:
    name: Run tests
    needs: [build-scan-trivy-repo]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upgrade dependencie pip
        run: python -m pip install --upgrade pip

      - name: Install dependence   
        run: pip install pytest pytest-md pytest-emoji pytest-cov   

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test with pytest
        run: pytest test/tests.py  
