name: Run Python tests

on:
  push:
    branches: ["main"]
    
jobs:

  build-scan-trivy-repo:
    permissions:
      id-token: write
      contents: read 
    name: run test trivy
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  build-test-pytest:
    name: Run tests
    needs: [build-scan-trivy-repo]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upgrade dependencie pip
        run: python -m pip install --upgrade pip

      - name: Install dependence   
        run: pip install pytest pytest-md pytest-emoji pytest-cov   

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test with pytest
        run: pytest test/tests.py   